import type { Metadata } from "next";
import { Lora, Raleway } from "next/font/google";
import { GeistSans } from 'geist/font';
import "./globals.css";

const lora = Lora({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lora",
});

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

// GeistSans is already optimized and doesn't need additional configuration
const geistSans = GeistSans;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${raleway.variable} ${geistSans.className} font-sans antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
